export const GET_GEOLOCATION_SUCCESS = "GET_GEOLOCATION_SUCCESS";
export const GET_GEOLOCATION_FAIL = "GET_GEOLOCATION_FAIL";

export const FETCH_INITIAL_NEARBY_SHOPS_SUCCESS = 'FETCH_INITIAL_NEARBY_SHOPS_SUCCESS';
export const FETCH_NEXT_NEARBY_SHOPS_SUCCESS = 'FETCH_NEXT_NEARBY_SHOPS_SUCCESS';
export const FETCH_NEARBY_SHOPS_FAIL = 'FETCH_NEARBY_SHOPS_FAIL';

export const FETCH_PREFERRED_SHOPS_SUCCESS = 'FETCH_PREFERRED_SHOPS_SUCCESS';
export const FETCH_PREFERRED_SHOPS_FAIL = 'FETCH_PREFERRED_SHOPS_FAIL';

export const REACTION_SUCCESS = 'REACTION_SUCCESS';
export const REACTION_FAIL = 'REACTION_FAIL';
