export const FETCH_NEARBY_SHOPS_SUCCESS = 'FETCH_NEARBY_SHOPS_SUCCESS';
export const FETCH_NEARBY_SHOPS_FAIL = 'FETCH_NEARBY_SHOPS_FAIL';

export const FETCH_PREFERRED_SHOPS_SUCCESS = 'FETCH_PREFERRED_SHOPS_SUCCESS';
export const FETCH_PREFERRED_SHOPS_FAIL = 'FETCH_PREFERRED_SHOPS_FAIL';

export const REACTION_SUCCESS = 'REACTION_SUCCESS';
export const REACTION_FAIL = 'REACTION_FAIL';
